require("./jasmine.console_reporter.js")
require("./jasmine.junit_reporter.js")
require("./jasmine.tap_reporter.js")
require("./jasmine.teamcity_reporter.js")
require("./jasmine.terminal_reporter.js")
